### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AIPTU3110** [Muqsit/EvdBeacon#4]
`Error: Call to undefined method pocketmine\nbt\tag\CompoundTag::hasTag()
File: plugins/EvdBeacon_dev-13.phar/src/muqsit/evdbeacon/block/tile/Beacon
Line: 106
Type: Error`

`Backtrace:
#0 pmsrc/src/block/tile/TileFactory(127): muqsit\evdbeacon\block\tile\Beacon->readSaveData(object pocketmine\nbt\tag\CompoundTag)
#1 pmsrc/src/world/World(2478): pocketmine\block\tile\TileFactory->createFromData(object pocketmine\world\World, object pocketmine\nbt\tag\CompoundTag)
#2 pmsrc/src/world/World(2429): pocketmine\world\World->initChunk(integer 13, integer 12, object pocketmine\world\format\Chunk)
#3 pmsrc/src/world/World(2762): pocketmine\world\World->loadChunk(integer 13, integer 12)
#4 pmsrc/src/world/World(2735): pocketmine\world\World->orderChunkPopulation(integer 13, integer 12, NULL )
#5 pmsrc/src/Server(600): pocketmine\world\World->requestChunkPopulation(integer 13, integer 12, NULL )
#6 pmsrc/src/network/mcpe/NetworkSession(239): pocketmine\Server->createPlayer(object pocketmine\network\mcpe\NetworkSession, object pocketmine\player\XboxLivePlayerInfo, boolean 1, object pocketmine\nbt\tag\CompoundTag)
#7 pmsrc/src/network/mcpe/NetworkSession(692): pocketmine\network\mcpe\NetworkSession->createPlayer()
#8 pmsrc/src/network/mcpe/handler/ResourcePacksPacketHandler(136): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#9 pmsrc/src/network/mcpe/protocol/ResourcePackClientResponsePacket(62): pocketmine\network\mcpe\handler\ResourcePacksPacketHandler->handleResourcePackClientResponse(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket)
#10 pmsrc/src/network/mcpe/NetworkSession(398): pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket->handle(object pocketmine\network\mcpe\handler\ResourcePacksPacketHandler)
#11 pmsrc/src/network/mcpe/NetworkSession(361): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ResourcePackClientResponsePacket, string[4] ....)
#12 pmsrc/src/network/mcpe/raklib/RakLibInterface(186): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[7] c.`a`..)
#13 pmsrc/vendor/pocketmine/raklib/src/server/ipc/RakLibToUserThreadMessageReceiver(43): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(integer 0, string[16] ...w..4.t!2EA@tI)
#14 pmsrc/src/network/mcpe/raklib/RakLibInterface(121): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface)
#15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(113): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#16 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(75): pocketmine\snooze\SleeperHandler->processNotifications()
#17 pmsrc/src/Server(1593): pocketmine\snooze\SleeperHandler->sleepUntil(double 1618992099.6187)
#18 pmsrc/src/Server(1143): pocketmine\Server->tickProcessor()
#19 pmsrc/src/PocketMine(276): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[39] /root/grytic/pmmp/PocketMine-MP/server/, string[47] /root/grytic/pmmp/PocketMine-MP/server/plugins/)
#20 pmsrc/src/PocketMine(299): pocketmine\server()
#21 pmsrc(11): require(string[83] phar:///root/grytic/pmmp/PocketMine-MP/server/PocketMine-MP.phar/src/PocketMine.)`

**Comment by Muqsit** [comment]
Fixed by #5
